energies_MeV: [1.0, 2.0]
ncones_theta: 8
theta_max_deg: 180.0
dr_mm: 1.0
rmax_cm: 2.0
ncases: 20000
ifull: 1
n_batch: 1
rng_seeds: [11111, 22222]
medium_name: H2O521ICRU
pegs4_data_file: 521icru.pegs4dat
write_cumulative: true
normalization: per_incident_energy_interacting_at_origin
norm_per_particle: 1.0
